runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^.*\.json
- ^dev/.*
- ^\..*
- ^lib/simplejson/tests/.*
- ^.*\.pyc

handlers:
- url: /.*
  script: zenchart.app

builtins:
- deferred: on

libraries:
- name: jinja2
  version: latest

